name: DBNet
backbone: 'deformable_resnet50'
pretrained: 'ckpts/dbnet/SynthText_DCN_ResNet50/[SynthText]-quad_hmean=0.5279-icdar_hmean=0.5113-det_hmean=0.5333.ckpt'
backbone_args:
  pretrained: True

fpn_args:
  in_chans: [256, 512, 1024, 2048]
  mid_chans: 256
  inplace: True

dbhead_args:
  in_chans: 256
  k: 50